# Generated by Django 4.1.7 on 2023-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_order_isrefunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isRefunded',
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_items',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
