# Generated by Django 4.1.7 on 2023-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_order_return_requested_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='all_costs',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
