# Generated by Django 4.1.7 on 2023-05-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prating',
            field=models.FloatField(default=0.0, verbose_name='Avg. Rating'),
        ),
    ]
