# Generated by Django 4.1.7 on 2023-05-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_prating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='psales_discount',
            field=models.FloatField(default=0.0, verbose_name='Sales Discount'),
        ),
    ]
