# Generated by Django 4.1.7 on 2023-05-04 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_Cart', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cshoppingcart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shopping_Cart.shoppingcart'),
        ),
    ]
