# Generated by Django 4.1.7 on 2023-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notificationList',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
