# Generated by Django 4.1.7 on 2023-05-10 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 10, 23, 6, 59, 41042)
            ),
        ),
    ]
