# Generated by Django 4.1.7 on 2023-05-26 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 26, 10, 45, 49, 626565)
            ),
        ),
    ]
