# Generated by Django 4.1.7 on 2023-06-08 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 8, 19, 38, 20, 393206)
            ),
        ),
    ]
