# Generated by Django 4.1.7 on 2023-06-11 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 11, 4, 38, 59, 62768)),
        ),
    ]
